
#ifndef CAMERA_PYTHON_H
#define CAMERA_PYTHON_H

#include <Python.h>

#include "python_helpers.h"

#define PYCAPSULE_TYPE_CAMERA "cameras.Camera._native_camera"

#define PYTHON_CAMERA_ADD_CONSTANTS(module) \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_RETURN_TO_MIDDLE); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_ZOOMED_OUT); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_ROTATE_RIGHT); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_ROTATE_LEFT); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_ENTERED_ROTATE_SURFACE); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_METAL_BELOW_WATER); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_FIX_IN_PLACE); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_UNKNOWN_8); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVING_INTO_MODE); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_STARTED_EXITING_C_UP); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_UNKNOWN_11); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_INIT_CAMERA); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_ALREADY_ZOOMED_OUT); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_C_UP_MODE); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_SUBMERGED); \
    PYTHON_ADD_CONSTANT(module, CAM_MOVE_PAUSE_SCREEN); \
    \
    PYTHON_ADD_CONSTANT(module, SHAKE_ATTACK); \
    PYTHON_ADD_CONSTANT(module, SHAKE_GROUND_POUND); \
    PYTHON_ADD_CONSTANT(module, SHAKE_SMALL_DAMAGE); \
    PYTHON_ADD_CONSTANT(module, SHAKE_MED_DAMAGE); \
    PYTHON_ADD_CONSTANT(module, SHAKE_LARGE_DAMAGE); \
    PYTHON_ADD_CONSTANT(module, SHAKE_HIT_FROM_BELOW); \
    PYTHON_ADD_CONSTANT(module, SHAKE_FALL_DAMAGE); \
    PYTHON_ADD_CONSTANT(module, SHAKE_SHOCK); \
    \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_EXPLOSION); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_BOWSER_THROW_BOUNCE); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_BOWSER_JUMP); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_UNUSED_5); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_UNUSED_6); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_UNUSED_7); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_PYRAMID_EXPLODE); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_JRB_SHIP_DRAIN); \
    PYTHON_ADD_CONSTANT(module, SHAKE_ENV_FALLING_BITS_PLAT); \
    \
    PYTHON_ADD_CONSTANT(module, SHAKE_FOV_SMALL); \
    PYTHON_ADD_CONSTANT(module, SHAKE_FOV_UNUSED); \
    PYTHON_ADD_CONSTANT(module, SHAKE_FOV_MEDIUM); \
    PYTHON_ADD_CONSTANT(module, SHAKE_FOV_LARGE); \
    \
    PYTHON_ADD_CONSTANT(module, SHAKE_POS_SMALL); \
    PYTHON_ADD_CONSTANT(module, SHAKE_POS_MEDIUM); \
    PYTHON_ADD_CONSTANT(module, SHAKE_POS_LARGE); \
    PYTHON_ADD_CONSTANT(module, SHAKE_POS_BOWLING_BALL);

struct GraphNode;
struct Camera;

struct _object *PyInit_cameras(void);
void python_camera_wrap(struct Camera *);
void python_camera_test_and_remove_state(struct GraphNode *);

#endif /* CAMERA_PYTHON_H */
