
#ifndef LEVEL_PYTHON_H
#define LEVEL_PYTHON_H

#include "types.h"

#include <ultra64.h>

#include <Python.h>

#include "surface_terrains.h"
#include "level_table.h"

#define PYTHON_LEVEL_ADD_CONSTANT(module, level) \
    PyModule_AddIntConstant(module, #level, level);

#define PYTHON_LEVEL_ADD_SURFACE_CONSTANTS(module) \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_DEFAULT); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_BURNING); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_0004); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_HANGABLE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_SLOW); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_DEATH_PLANE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CLOSE_CAMERA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_WATER); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_FLOWING_WATER); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_INTANGIBLE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_VERY_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NOT_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_TTM_VINES); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_MGR_MUSIC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_INSTANT_WARP_1B); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_INSTANT_WARP_1C); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_INSTANT_WARP_1D); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_INSTANT_WARP_1E); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_SHALLOW_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_DEEP_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_INSTANT_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_DEEP_MOVING_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_SHALLOW_MOVING_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_MOVING_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_WALL_MISC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NOISE_DEFAULT); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NOISE_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_HORIZONTAL_WIND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_INSTANT_MOVING_QUICKSAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_ICE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_LOOK_UP_WARP); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_HARD); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_WARP); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_TIMER_START); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_TIMER_END); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_HARD_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_HARD_VERY_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_HARD_NOT_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_VERTICAL_WIND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_BOSS_FIGHT_CAMERA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CAMERA_FREE_ROAM); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_THI3_WALLKICK); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CAMERA_8_DIR); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CAMERA_MIDDLE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CAMERA_ROTATE_RIGHT); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CAMERA_ROTATE_LEFT); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CAMERA_BOUNDARY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NOISE_VERY_SLIPPERY_73); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NOISE_VERY_SLIPPERY_74); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NOISE_VERY_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NO_CAM_COLLISION); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NO_CAM_COLLISION_77); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NO_CAM_COL_VERY_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_NO_CAM_COL_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_SWITCH); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_VANISH_CAP_WALLS); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_A6); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_A7); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_A8); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_A9); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_AA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_AB); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_AC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_AD); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_AE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_AF); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B0); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B1); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B2); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B3); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B4); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B5); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B6); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B7); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B8); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_B9); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_BA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_BB); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_BC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_BD); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_BE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_BF); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C0); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C1); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C2); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C3); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C4); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C5); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C6); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C7); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C8); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_C9); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_CA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_CB); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_CC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_CD); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_CE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_CF); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_D0); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_D1); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WOBBLE_D2); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_D3); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_D4); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_D5); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_D6); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_D7); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_D8); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_D9); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_DA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_DB); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_DC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_DD); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_DE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_DF); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E0); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E1); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E2); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E3); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E4); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E5); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E6); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E7); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E8); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_E9); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_EA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_EB); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_EC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_ED); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_EE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_EF); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_F0); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_F1); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_F2); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_F3); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_TTC_PAINTING_1); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_TTC_PAINTING_2); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_TTC_PAINTING_3); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_F7); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_F8); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_F9); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_FA); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_FB); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_PAINTING_WARP_FC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_WOBBLING_WARP); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_TRAPDOOR); \
    \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CLASS_DEFAULT); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CLASS_VERY_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CLASS_SLIPPERY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_CLASS_NOT_SLIPPERY); \
    \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_FLAG_DYNAMIC); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_FLAG_NO_CAM_COLLISION); \
    PYTHON_LEVEL_ADD_CONSTANT(module, SURFACE_FLAG_X_PROJECTION); \

#define PYTHON_LEVEL_ADD_TERRAIN_CONSTANTS(module) \
    /* These are effectively unique "surface" types like those defined higher */ \
    /* And they are used as collision commands to load certain functions */ \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_LOAD_VERTICES); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_LOAD_CONTINUE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_LOAD_END); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_LOAD_OBJECTS); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_LOAD_ENVIRONMENT); \
    \
    /* Terrain types defined by the level script command terrain_type (cmd_31) */ \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_GRASS); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_STONE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_SNOW); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_SAND); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_SPOOKY); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_WATER); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_SLIDE); \
    PYTHON_LEVEL_ADD_CONSTANT(module, TERRAIN_MASK);

#define PYTHON_LEVEL_ADD_LEVEL_CONSTANTS(module) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BBH) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_CCM) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_CASTLE) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_HMC) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_SSL) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BOB) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_SL) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_WDW) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_JRB) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_THI) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_TTC) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_RR) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_CASTLE_GROUNDS) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BITDW) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_VCUTM) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BITFS) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_SA) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BITS) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_LLL) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_DDD) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_WF) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_ENDING) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_CASTLE_COURTYARD) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_PSS) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_COTMC) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_TOTWC) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BOWSER_1) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_WMOTR) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_UNKNOWN_32) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BOWSER_2) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_BOWSER_3) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_UNKNOWN_35) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_TTM) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_UNKNOWN_37) \
    PYTHON_LEVEL_ADD_CONSTANT(module, LEVEL_UNKNOWN_38)

PyObject* PyInit_levels(void);

#endif /* LEVEL_PYTHON_H */
